name: project_getCodeConfigSave

authors:
  - Asiya Shaji

type: SUITE

init:
 - create_GitHubacc_abstract
 - create_project_GitHub_abstract

endpoint: /projects/{{@create_project_GitHub_abstract_Response.data.id}}/autocodeconfig

method: GET

auth: Default

headers:
- 'Content-Type: application/json'


assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data != EMPTY"
  #cleanup:
 # - delete_project

severity: Major

category: Functional

tags:
- V2
