name: project_getCodeConfigSave_abstract

authors:
  - Asiya Shaji

type: ABSTRACT

endpoint: /projects/{{@create_project_GitHub_abstract_Response.data.id}}/autocodeconfig

method: GET

auth: Default

headers:
- 'Content-Type: application/json'

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data != EMPTY"

severity: Major

category: Functional

tags:
- V2
